### ISSUE TITLE
"Child process * exited with status 255"

### ISSUE THREAD

**Issue by codemonies** [samuel-allan/FastProxyChecker#2]
Hello,

Initially I was encountering an issue with the number of open sockets on lists with 1,000+ proxies.

I fixed this by wrapping the following into chunks:

```
    $results[] = multiRequest($data);
```

Like so:

```
    $data = array_chunk($data,25);
    foreach ($data as $data) {
        $results[] = multiRequest($data);
    }
    $results = array_unique(call_user_func_array('array_merge', $results));
```

The above would limit multiRequest to 25 concurrent requests. I would suggest adding this to master.

The persistent issue I am now seeing in the Apache logs is this:
"Parent: child process \* exited with status 255 -- Restarting."

As per [this](http://stackoverflow.com/questions/1138269/apache-error-notice-parent-child-process-exited-with-status-3221225477-res) thread, I tried adding this to httpd.conf to no avail:

```
    <IfModule mpm_winnt_module>
        ThreadStackSize 8888888
    </IfModule>
```

Can we add something to skip the proxy when its child process exits?

**Comment by codemonies** [comment]
As suggested [here](http://stackoverflow.com/questions/31423295/curl-multi-xxx-cause-connection-reset), upgrading PHP cURL to the latest version fixed it.

This is a great script. Thank you!

**Comment by samuel-allan** [comment]
Hey, thanks a lot for pointing that out!
With the number of proxies you are dealing with, it is definitely wrong to do it on a proxy-per-thread basis, and I will certainly fix this issue, however, there are two problems here: first, should it be a parameter (proxies per thread, or max threads?), and if so, what default value could be a adequate solution for most cases? (This point will probably require extensive testing I feel).

**Comment by natesreich** [comment]
​Hi Samuel,

Thanks for the great work!

I feel by having multiple proxies per thread, it would slow down the
process too much.

Adding maximum threads makes sense in any case. For example, if you're
using an API like https://api.ipify.org/ to determine the end IP address,
having too many simultaneous threads might hurt their service. Especially
since we're testing a proxy, it might make it difficult for their service
to block our requests if they're being overloaded. It might even be
construed as a DDoS attack, which is the last thing we would want.

Thus, I broke down the maximum threads into groups of 25 like this:

$data = array_chunk($data,25);
> foreach ($data as $data) {
>      $results[] = multiRequest($data);
> }
> $results = array_unique(call_user_func_array('array_merge', $results));


It seems to be working really well. I even upped it to chunks of 100, and
it's still holding up extremely well.

Nathan Reich

**Comment by codemonies** [comment]
I think having multiple proxies per thread would slow down the service too much. The beauty of this script is in the multi-threading.

However, leaving "maximum threads" open could be detrimental to any third-party service you're calling in the cURL script (for example, "http://whatismyipaddress.com/" in the master script).

This is why I would suggest adding a maximum thread limit by default.

I believe the code I posted above should achieve this objective. I even upped the chunks to 100, and it's still holding up extremely well.
